FROM python:3.10-slim

COPY jaffle_dagster/requirements.txt .

RUN pip install -r requirements.txt

#RUN pip install \
#    dagster \
#    dagster-graphql \
#    dagster-webserver \
#    dagster-postgres \
#    dagster-docker

# Set $DAGSTER_HOME and copy dagster.yaml and workspace.yaml there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY jaffle_dagster/dagster.yaml jaffle_dagster/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME